import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Build output
    "dist/**",
    "build/**",
    // Stale Next.js build artifacts — pre-cutover checkouts (and dev servers
    // stopped after the cutover) may still carry these dirs on disk
    ".next/**",
    ".next-e2e/**",
    // Docker entrypoint uses CommonJS require
    "docker-entrypoint.js",
    // Convex generated code (regenerated by `bunx convex dev`)
    "convex/_generated/**",
    // Generated route tree (regenerated by the Start plugin on dev/build)
    "src/routeTree.gen.ts",
  ]),
]);

export default eslintConfig;
