/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LeaderboardVisualRouteImport } from './routes/leaderboard-visual'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueIndexRouteImport } from './routes/league.index'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league.$leagueId.index'
import { Route as LeagueLeagueIdSplatRouteImport } from './routes/league.$leagueId.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardVisualRoute = LeaderboardVisualRouteImport.update({
  id: '/leaderboard-visual',
  path: '/leaderboard-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/league/',
  path: '/league/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/league/$leagueId/',
  path: '/league/$leagueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdSplatRoute = LeagueLeagueIdSplatRouteImport.update({
  id: '/league/$leagueId/$',
  path: '/league/$leagueId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard-visual': typeof LeaderboardVisualRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/league/': typeof LeagueIndexRoute
  '/league/$leagueId/$': typeof LeagueLeagueIdSplatRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard-visual': typeof LeaderboardVisualRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/league': typeof LeagueIndexRoute
  '/league/$leagueId/$': typeof LeagueLeagueIdSplatRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard-visual': typeof LeaderboardVisualRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/league/': typeof LeagueIndexRoute
  '/league/$leagueId/$': typeof LeagueLeagueIdSplatRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard-visual'
    | '/pricing'
    | '/settings'
    | '/league/'
    | '/league/$leagueId/$'
    | '/league/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard-visual'
    | '/pricing'
    | '/settings'
    | '/league'
    | '/league/$leagueId/$'
    | '/league/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard-visual'
    | '/pricing'
    | '/settings'
    | '/league/'
    | '/league/$leagueId/$'
    | '/league/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardVisualRoute: typeof LeaderboardVisualRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  LeagueIndexRoute: typeof LeagueIndexRoute
  LeagueLeagueIdSplatRoute: typeof LeagueLeagueIdSplatRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard-visual': {
      id: '/leaderboard-visual'
      path: '/leaderboard-visual'
      fullPath: '/leaderboard-visual'
      preLoaderRoute: typeof LeaderboardVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/': {
      id: '/league/'
      path: '/league'
      fullPath: '/league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/$': {
      id: '/league/$leagueId/$'
      path: '/league/$leagueId/$'
      fullPath: '/league/$leagueId/$'
      preLoaderRoute: typeof LeagueLeagueIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardVisualRoute: LeaderboardVisualRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  LeagueIndexRoute: LeagueIndexRoute,
  LeagueLeagueIdSplatRoute: LeagueLeagueIdSplatRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
